---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/flexys/docker-compose-in-concourse.git
    branch: master



jobs:
- name: docker-compose-test
  public: true
  plan:
  - get: repo
    trigger: true
  - task: build
    privileged: true
    file: test/build.yaml
