---
resources:
- name: test
  type: git
  source:
    uri: https://github.com:mbcx4jrh/test.git
    branch: master



jobs:
- name: docker-compose-test
  public: true
  plan:
  - get: test
  - task: build
    file: test/build.yaml
